import { StyleSheet } from 'react-native';
import metrics from './metrics';
import colors from './colors';
import fonts from './fonts';

const theme = StyleSheet.create({
    // pages
    container: {
        flex: 1,
        backgroundColor: colors.primary,
        justifyContent: 'flex-start',
        paddingLeft: metrics.baseMargin,
        paddingRight: metrics.baseMargin,
    },
    containerPrimary: {
        flex: 1,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    containerSuccess: {
        flex: 1,
        backgroundColor: colors.green,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    containerLoading: {
        flex: 1,
        backgroundColor: colors.secondary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    containerBlank: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flex: 1,
        paddingLeft: metrics.baseMargin,
        paddingRight: metrics.baseMargin,
        paddingVertical: 20,
    },
    contentCenter: {
        flex: 1,
        paddingLeft: metrics.baseMargin,
        paddingRight: metrics.baseMargin,
        justifyContent: 'center',
        alignItems: 'center',
    },
    space: {
        margin: metrics.largeMargin,
    },
    section: {
        margin: metrics.baseMargin,
    },
    sectionTitle: {
        color: colors.dark,
        fontWeight: 'bold',
        fontSize: fonts.regular,
        alignSelf: 'center',
        marginBottom: metrics.largeMargin,
    },
    row: {
        marginTop: metrics.baseMargin,
    },
    center: {
        margin: metrics.smallMargin,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    centerFlex: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    centerFlexSpace: {
        flex: 1,
        paddingVertical: 30,
        paddingHorizontal: metrics.baseMargin,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    centerText: {
        flex: 1,
        marginTop: '50%',
        height: '100%',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottom: {
        position: 'absolute',
        bottom: 20,
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    boxAnuncio: {
        flex: 1,
        flexDirection: 'row',
        // flexWrap: 'wrap',
        paddingHorizontal: 5,
        paddingVertical: 5,
    },
    blockAnuncio: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        margin: metrics.smallMargin,
        marginBottom: 5,
        width: metrics.screenWidth / 2 - 15,
        height: metrics.screenWidth / 2 - 15,
        borderRadius: metrics.baseRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    bodyAnuncio: {
        padding: metrics.baseMargin,

    },
    elevation: {
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
    },
    boxTitleAnuncio: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    footerAnuncio: {
        flex: 1,
        backgroundColor: '#00000060',
        borderBottomLeftRadius: metrics.baseRadius,
        borderBottomRightRadius: metrics.baseRadius,
        position: 'absolute',
        bottom: 0,
        width: '100%',
        height: 25,
        justifyContent: 'center',
        paddingLeft: 15,
    },
    // header
    header: {
        elevation: 0,
        backgroundColor: colors.primary,
        height: metrics.headerHeight,
        borderBottomWidth: 0,
    },
    box: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: colors.secondary,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: metrics.baseRadius,
    },
    headerTitle: {
        color: colors.light,
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.large,
        alignSelf: 'center',
        textAlign: 'center',
        marginVertical: 20,
    },
    headerSubtitle: {
        flex:1,
        color: colors.light,
        fontFamily: 'Montserrat',
        fontSize: fonts.large,
        alignSelf: 'center',
        textAlign: 'center',
    },
    headerButton: {
        marginTop: metrics.statusBarHeight,
        width: 24,
        height: 24,
        marginLeft: metrics.largeMargin,
        marginRight: metrics.largeMargin,
        alignSelf: 'flex-start',
    },
    headerImg: {
        width: 120,
        height: 50,
        flex: 1,
        marginLeft: 10,
    },
    headerRight: {
        marginLeft: 10,
        marginRight: 10,
    },
    // modals
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modal: {
        justifyContent: 'center',
        backgroundColor: colors.background,
        borderRadius: metrics.baseRadius,
        width: '70%',
    },
    modalLarge: {
        justifyContent: 'center',
        backgroundColor: colors.background,
        borderRadius: metrics.baseRadius,
        width: '90%',
        padding: 10,
    },
    modalLoad: {
        padding: metrics.largeMargin,
        backgroundColor: colors.background,
        borderRadius: metrics.baseRadius,
        alignItems: 'center',
        justifyContent: 'center',
        width: 70,
        height: 70,
    },
    closeButton: {
        position: 'absolute',
        right: 0,
        top: 2,
        zIndex: 10,
    },
    titleModal: {
        flexDirection: "row",
        justifyContent: 'center',
        marginLeft: -40,
    },
    // texts
    input: {
        backgroundColor: colors.light,
        fontSize: fonts.regular,
        color: colors.dark,
        fontFamily: 'Montserrat-Regular',
        paddingLeft: 15,
        paddingRight: 15,
        paddingBottom: 8,
        paddingTop: 8,
        marginBottom: 15,
        borderRadius: metrics.baseRadius,
        minHeight: 40,
    },
    inputSearch: {
        backgroundColor: colors.grey,
        fontSize: fonts.regular,
        color: colors.black,
        fontFamily: 'Montserrat-Regular',
        paddingLeft: 15,
        paddingRight: 15,
        paddingBottom: 8,
        paddingTop: 8,
        marginBottom: 15,
        borderRadius: metrics.baseRadius,
        minHeight: 40,
    },
    placeholder: {
        fontFamily: 'Montserrat-Regular',
    },
    inputLight: {
        paddingLeft: 10,
        paddingRight: 10,
        paddingBottom: 5,
        paddingTop: 5,
        fontSize: fonts.regular,
        color: colors.light,
    },
    searchInput: {
        paddingLeft: 10,
        paddingRight: 10,
        paddingBottom: 5,
        paddingTop: 5,
        fontSize: fonts.regular,
        color: colors.dark,
        width: '85%',
    },
    textContent: {
        fontFamily: 'Montserrat-Regular',
        textAlign: 'center',
        padding: metrics.baseMargin,
        marginLeft: 40,
        fontSize: fonts.regular,
        color: colors.dark,
        fontWeight: 'bold',
        width: '100%',
    },
    textPage: {
        fontFamily: 'Montserrat-Regular',
        padding: metrics.baseMargin,
        fontSize: fonts.regular,
        color: colors.grey,
        width: '100%',
        textAlign: 'center',
    },
    textPrimary: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.regular,
        color: colors.primary,
    },
    textDefault: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.regular,
        color: colors.dark,
        padding: metrics.smallMargin,
    },
    textSmall: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.small,
        color: colors.light,
        marginBottom: 10,
    },
    textPageLeft: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.regular,
        color: colors.grey,
    },
    blockTitle: {
        color: colors.light,
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.regular,
        marginTop: 20,
    },
    subtitle: {
        color: colors.dark,
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.regular,
    },
    label: {
        fontFamily: 'Montserrat-Regular',
        padding: metrics.baseMargin,
        fontSize: fonts.medium,
        color: colors.dark,
        textAlign: 'center',
    },
    copyright: {
        textAlign: 'center',
        marginTop: metrics.largeMargin,
        padding: metrics.baseMargin,
        fontSize: fonts.regular,
        color: colors.secondary,
        fontWeight: 'bold',
        width: '100%',
    },
    title: {
        color: colors.primary,
        fontSize: fonts.regular,
        fontWeight: 'bold',
        textAlign: 'left',
    },
    titleLarge: {
        fontFamily: 'Montserrat-Bold',
        marginTop: 20,
        marginBottom: 10,
        color: colors.primary,
        fontSize: fonts.large,
        textAlign: 'center',
    },
    titleAnuncio: {
        marginVertical: 2,
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.regular,
        color: colors.dark,
    },
    precoAnuncio: {
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.regular,
        color: colors.primary,
    },
    menuSubtitle: {
        color: colors.grey,
        fontSize: fonts.small,
        textAlign: 'center',
    },
    menuTitle: {
        color: colors.dark,
        fontSize: fonts.regular,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    // images
    icon: {
        width: 24,
        height: 24,
    },
    iconLarge: {
        width: 54,
        height: 54,
        alignSelf: 'center',
    },
    iconHead: {
        width: '50%',
        height: 70,
        alignSelf: 'center',
    },
    featured: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
        borderRadius: metrics.baseRadius,
    },
    thumbnail: {
        width: 30,
        height: 30,
    },
    iconDefault: {
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: metrics.roundRadius,
        backgroundColor: colors.primary,
    },
    centerIcon: {
        marginTop: 20,
        alignSelf: 'center',
    },
    img: {
        width: 250,
        height: 250,
        alignSelf: 'center',
    },
    fullImg: {
        width: metrics.screenWidth,
        aspectRatio: 1,
    },
    imgAnuncio: {
        width: metrics.screenWidth,
        height: metrics.screenHeight / 3,
    },
    // buttons
    btnHeader: {
        paddingHorizontal: 15,
        paddingVertical: 15,
    },
    btnPrimary: {
        backgroundColor: colors.primary,
    },
    btnTransparent: {
        paddingLeft: 15,
        paddingRight: 15,
        paddingTop: 10,
        paddingBottom: 10,
        // justifyContent: 'space-between',
        flexDirection: "row",
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnColored: {
        maxWidth: '50%',
        paddingLeft: 15,
        paddingRight: 15,
        paddingTop: 10,
        paddingBottom: 10,
        justifyContent: 'space-between',
        flexDirection: "row",
        alignItems: 'center',
        backgroundColor: colors.secondary,
        borderRadius: metrics.baseRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    btnLiked: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.red,
        borderRadius: metrics.roundRadius,
        position: 'absolute',
        right: 10,
        bottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    btnUnliked: {
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.light,
        borderRadius: metrics.roundRadius,
        position: 'absolute',
        right: 10,
        bottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    btnLikedLg: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.red,
        borderRadius: metrics.roundRadius,
        position: 'absolute',
        right: 10,
        top: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    btnUnlikedLg: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.light,
        borderRadius: metrics.roundRadius,
        position: 'absolute',
        right: 10,
        top: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    btnShare: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.backgroundOverlay,
        borderRadius: metrics.roundRadius,
        position: 'absolute',
        right: 10,
        bottom: 10,
    },
    btnWhatsapp: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#25d366',
        borderRadius: metrics.roundRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 6,
    },
    btnTipoGradient: {
        backgroundColor: colors.primary,
        width: '40%',
        height: 35,
        borderRadius: metrics.baseRadius,
        justifyContent: 'center',
        flexDirection: "row",
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 6,
    },
    badgeTipoGradient: {
        paddingLeft: 5,
        paddingRight: 5,
        borderRadius: metrics.baseRadius,
        justifyContent: 'center',
        flexDirection: "row",
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    btnFacebook: {
        // flex: 1,
        height: 40,
        paddingLeft: 15,
        paddingRight: 15,
        paddingTop: 10,
        paddingBottom: 10,
        flexDirection: "row",
        alignItems: 'center',
        backgroundColor: '#3b5998',
        borderRadius: metrics.roundRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    btnGoogle: {
        // flex: 1,
        height: 40,
        paddingLeft: 15,
        paddingRight: 15,
        paddingTop: 10,
        paddingBottom: 10,
        flexDirection: "row",
        alignItems: 'center',
        backgroundColor: colors.light,
        borderRadius: metrics.roundRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    largeButton: {
        backgroundColor: colors.primary,
        height: 50,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: metrics.roundRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    mediumButton: {
        backgroundColor: colors.primary,
        height: 40,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: metrics.roundRadius,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    listItemBlock: {
        backgroundColor: colors.background,
        height: 60,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomColor: colors.light,
        borderBottomWidth: 1,
        paddingLeft: 30,
    },
    listItemBlockCenter: {
        backgroundColor: colors.background,
        height: 50,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomColor: colors.light,
        borderBottomWidth: 1,
    },
    linkButton: {
        marginBottom: 15,
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.regular,
        color: colors.primary,
    },
    btnIcon: {
        width: 16,
        height: 16,
        alignSelf: 'center',
    },
    btnIconAlone: {
        width: 16,
        height: 16,
        alignSelf: 'center',
    },
    btnIconLarge: {
        width: 22,
        height: 22,
        alignSelf: 'center',
    },
    btnText: {
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.medium,
        color: colors.light,
        alignSelf: 'center',
    },
    btnTextGradient: {
        fontFamily: 'Montserrat',
        fontSize: fonts.regular,
        color: colors.light,
        alignSelf: 'center',
        backgroundColor: 'transparent',
    },
    badgeText: {
        fontFamily: 'Montserrat-Bold',
        fontSize: fonts.small,
        color: colors.light,
        alignSelf: 'center',
    },
    btnTextLeft: {
        marginLeft: metrics.smallMargin,
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.medium,
        color: colors.light,
    },
    btnTextDark: {
        fontSize: fonts.medium,
        fontWeight: 'bold',
        color: colors.dark,
        alignSelf: 'center',
    },
    btnTextCenter: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.large,
        color: colors.light,
        textAlign:'center',
        paddingRight : 10,
        marginBottom: 4,
    },
    btnTextCenterMedium: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.regular,
        color: colors.light,
        textAlign:'center',
        paddingRight : 10,
    },
    btnList: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.large,
        color: colors.dark,
        textAlign:'center',
        paddingHorizontal: 10,
    },
    btnListPrimary: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.large,
        color: colors.primary,
        textAlign:'center',
        paddingHorizontal : 10,
    },
    btnListError: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.large,
        color: colors.red,
        textAlign:'center',
        paddingHorizontal : 10,
    },
    btnTextColored: {
        fontFamily: 'Montserrat-Regular',
        fontSize: fonts.medium,
        color: colors.primary,
        alignSelf: 'center',
    },
    iconTabRound: {
        width: 70,
        height: 70,
        backgroundColor: colors.primary,
        borderRadius: metrics.roundRadius,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    }
});

export default theme;